version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: mern_microservices-mongo   # renamed container
    ports:
      - "27017:27017"   # expose for local debugging
    volumes:
      - mongo-data:/data/db   # persist MongoDB data

  hello-service:
    build: ./backend/helloService
    ports:
      - "3001:3001"
    env_file:
      - ./backend/helloService/.env
    depends_on:
      - mongo

  profile-service:
    build: ./backend/profileService
    ports:
      - "3002:3002"
    env_file:
      - ./backend/profileService/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/helloWorld   # 👈 still use "mongo" (service name), not container name
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8090:80"   # Changed from 8080 to 8090
    depends_on:
      - hello-service
      - profile-service

volumes:
  mongo-data:
